name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/npxl-viewer && mv target/release/npxl-viewer target/release/npxl-viewer_amd64

      - name: Upload release
        uses: actions/upload-artifact@v3
        with:
          name: npxl-viewer-darwin
          path: target/release/npxl-viewer_amd64

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Upload release
        uses: actions/upload-artifact@v3
        with:
          name: npxl-viewer-darwin
          path: target/release/npxl-viewer.exe

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --all --release && strip target/release/npxl-viewer && mv target/release/npxl-viewer target/release/npxl-viewer_darwin

      - name: Upload release
        uses: actions/upload-artifact@v3
        with:
          name: npxl-viewer-darwin
          path: target/release/npxl-viewer_darwin
